# Assignment 
## <font color="blue">System_of_Linear_Equations</font>
##### `Queeny Mae Escabarte`
---

# <font color = red> Assignment 1 </font>
---

- The below python functions are developed to automate forward elimination.

In [12]:
# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

- To complete the process of determining the solution, create a function or steps of function that will automate backward substitution.

In [15]:
import numpy as np

def BackwardSubstitution(Ab):
    m, n = Ab.shape
    x = np.zeros(m)

    for i in range(m - 1, -1, -1):
        x[i] = Ab[i, n - 1] / Ab[i, i]
        for k in range(i - 1, -1, -1):
            Ab[k, n - 1] -= Ab[k, i] * x[i]
    
    return x


Ab = np.array([
    [2, 1, -1, 8],
    [0, -3, 2, 1],
    [0, 0, 4, 6]
], dtype=float)

# Call BackwardSubstitution
solution = BackwardSubstitution(Ab)
print("Solution Vector (x):", solution)

Solution Vector (x): [4.41666667 0.66666667 1.5       ]


# <font color = red> Assignment 2 </font>
---

---
1. Provide reasons why each of the following equations is, or is not, a linear equation.

- $\cos{\theta}x+4y+z = \sqrt{3}$ <br>
This equation is not linear because it involves the product of the variable $ x $ and the non-constant function $\cos{\theta}$.
- $\cos{x}4y+z = \sqrt{3}$<br>
This equation is not linear. It contains the product of $ 4y $ and $ \cos x $, which makes it non-linear.
- $x^{-1}+7y+z = \sin{(\frac{\pi}{2})}$<br>
This equation is not linear. The presence of the term $x^-1$ (inverse of $ x $) makes it non-linear.
- $x^1+y^1+z^1=0$<br>
This equation is linear. All the variables $(x,,y,z)$ are raised to the power of 1, and there are no products or other non-linear operations. The sum of the variables to the power of 1 on the left side and the constant term on the right side makes it a linear equation.

2. Find the solutions to the linear equations:
 - $2x_1+3x_2 =5$ <br> 
$x_2 = s$ <br>
$2x_1+3s =5$.<br>
$x_1 = \frac{5-3s}{2}$.<br>
\begin{pmatrix}
    1 & 0 &\bigm| & \frac{5-3s}{2} \\
    0 & 1 &\bigm| & s \\
\end{pmatrix}<br>
- $4x_1+3x_2+2x_3=1$ <br>
$x_2 = s$ <br> $x_3 = t$ <br>
$4x_1+3s+2t=1$.<br>
$x_1 = \frac{1-3s-2t}{4}$.<br>
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & \frac{1-3s-2t}{4} \\
    0 & 1 & 0 &\bigm| & s \\
    0 & 0 & 1 &\bigm| & t \\
\end{pmatrix}<br>
- $3x-6y=0$ <br>
$y = s$ <br> the new equation becomes: $3x-6s =0$.<br>
$x = 6s$.<br>
\begin{pmatrix}
    1 & 0 &\bigm| & 2s \\
    0 & 1 &\bigm| & s \\
\end{pmatrix}<br>​



In [10]:
# 2
import sympy as sp
x1, x2, x3 = sp.symbols('x1 x2 x3')
equation1 = sp.Eq(2*x1 + 3*x2, 5)
equation2 = sp.Eq(4*x1 + 3*x2 + 2*x3, 1)

solution1 = sp.solve(equation1, (x1, x2))
solution2 = sp.solve(equation2, (x1, x2))
print("Answer: ")
print(solution1)

print("\n\nAnswer: ")
print(solution2)

Answer: 
[(5/2 - 3*x2/2, x2)]


Answer: 
[(-3*x2/4 - x3/2 + 1/4, x2)]


3. Solve the following systems of linear equations<br>
a.<br> 
\begin{equation}
x-y=0 \\
2x+y = 3
\end{equation}
<br>
Solution:
- $2(x - y = 0)  \Rightarrow    2x - 2y = 0  \Rightarrow   2x - 2y = 0 - 2x + y = 3  \Rightarrow   3y = 3  \Rightarrow  y = 1$
- $x - y = 0  =>  x - 1 = 0  =>  x = 1$
<br>
<br>
$
\begin{pmatrix}
    1 & -1 &\bigm| & 0 \\
    2 & 1  &\bigm| & 3 \\
\end{pmatrix}
\rightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & -1 &\bigm| & 0 \\
    0 & 3  &\bigm| & 3 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & -1 &\bigm| & 0 \\
    0 & 3  &\bigm| & 3 \\
\end{pmatrix}
\rightarrow{\frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & -1 &\bigm| & 0 \\
    0 & 1  &\bigm| & 1 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & -1 &\bigm| & 0 \\
    0 & 1  &\bigm| & 1 \\
\end{pmatrix}
\rightarrow{\text{R}_{1} + \text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 1 \\
    0 & 1  &\bigm| & 1 \\
\end{pmatrix}
$
<br>
<br>
\begin{align}
x=1 \\
y=1
\end{align}

In [16]:
# 3.a
import numpy as np
A = np.array([[1, -1, 0], [2, 1, 3]])

A1 = RowAdd(A, 0, 1, -2)
print("A1:")
print(A1)
A2 = RowScale(A, 1, 1/3)
print("A2:")
print(A2,)
A3 = RowAdd(A, 1, 0, 1)
print("A3:")
print(A3)

print("Solutions x, y:")
print(BackwardSubstitution(A3))

A1
[[ 1. -1.  0.]
 [ 0.  3.  3.]]
A2
[[ 1.         -1.          0.        ]
 [ 0.66666667  0.33333333  1.        ]]
A3
[[3. 0. 3.]
 [2. 1. 3.]]
Solutions x, y:
[1. 3.]


b. 
\begin{align}
    x + 5y &= -1 \\
    -x + y &= -5 \\
    2x + 4y &= 4
\end{align}

Solution:
\begin{align}
    x + 5y &= -1 \quad \Rightarrow \quad 6y = -6 \quad \Rightarrow \quad y = -1 \\
    x + 5(-1) &= -1 \quad \Rightarrow \quad x - 5 = -1 \quad \Rightarrow \quad x = -1 + 5 \quad \Rightarrow \quad x = 4
\end{align}

<br>
\begin{align}
    \begin{pmatrix}
        1 & 5 &\bigm| & -1 \\
        -1 & 1 &\bigm| & -5 \\
        2 & 4 &\bigm| & 4 \\
    \end{pmatrix}
    \xrightarrow{R_2 + R_1}
    \begin{pmatrix}
        1 & 5 &\bigm| & -1 \\
        0 & 6 &\bigm| & -6 \\
        2 & 4 &\bigm| & 4 \\
    \end{pmatrix}
    \xrightarrow{R_3 - 2R_1}
    \begin{pmatrix}
        1 & 5 &\bigm| & -1 \\
        0 & 6 &\bigm| & -6 \\
        0 & -6 &\bigm| & 6 \\
    \end{pmatrix}
    \xrightarrow{\frac{R_2}{6}}
    \begin{pmatrix}
        1 & 5 &\bigm| & -1 \\
        0 & 1 &\bigm| & -1 \\
        0 & -6 &\bigm| & 6 \\
    \end{pmatrix}
\end{align}

\begin{align}
    \begin{pmatrix}
        1 & 5 &\bigm| & -1 \\
        0 & 1 &\bigm| & -1 \\
        0 & -6 &\bigm| & 6 \\
    \end{pmatrix}
    \xrightarrow{R_1 - 5 \cdot R_2}
    \begin{pmatrix}
        1 & 0 &\bigm| & 4 \\
        0 & 1 &\bigm| & -1 \\
        0 & -6 &\bigm| & 6 \\
    \end{pmatrix}
    \xrightarrow{R_3 + 6 \cdot R_2}
    \begin{pmatrix}
        1 & 0 &\bigm| & 4 \\
        0 & 1 &\bigm| & -1 \\
        0 & 0 &\bigm| & 0 \\
    \end{pmatrix}
\end{align}

\begin{align}
    x &= 4 \\
    y &= -1
\end{align}


In [29]:
# b
import numpy as np
A=np.array([[1,5,-1],[-1,1,-5],[2,4,4]])

A1 = RowAdd(A,0,1,1)
print("Eq1:")
print(A1)
A2 = RowAdd(A1,0,2,-2)
print("Eq2:")
print(A2)
A3 = RowScale(A2,1,0.33)
print("Eq3:")
print(A3)
A4 = RowAdd(A3,1,0,-5)
print("Eq4:")
print(A4)
A5 = RowAdd(A4,1,2,6)
print("Eq5:")
print(A5)

print("Solutions x, y:")
print(BackwardSubstitution(A5))

Eq1:
[[ 1.  5. -1.]
 [ 0.  6. -6.]
 [ 2.  4.  4.]]
Eq2:
[[ 1.  5. -1.]
 [ 0.  6. -6.]
 [ 0. -6.  6.]]
Eq3:
[[ 1.    5.   -1.  ]
 [ 0.    1.98 -1.98]
 [ 0.   -6.    6.  ]]
Eq4:
[[ 1.   -4.9   8.9 ]
 [ 0.    1.98 -1.98]
 [ 0.   -6.    6.  ]]
Eq5:
[[ 1.   -4.9   8.9 ]
 [ 0.    1.98 -1.98]
 [ 0.    5.88 -5.88]]
Solutions x, y:
[0. 0. 1.]


c. <br> 
\begin{align}
2x_1+3x_2-x_3= -1 \\
x_1+x_3 = 0 \\
-x_1+2x_2-2x_3 = 0
\end{align}
<br>
$
\begin{pmatrix}
    2 & 3 & -1 &\bigm| & -1 \\
    1 & 0 & 1  &\bigm| & 0 \\
    -1 & 2 & -2  &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{2}\text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & -\frac{1}{2}  &\bigm| & -\frac{1}{2} \\
    1 & 0 & 1  &\bigm| & 0 \\
    -1 & 2 & -2  &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & -\frac{1}{2}  &\bigm| & -\frac{1}{2} \\
    0 & -\frac{3}{2} & \frac{3}{2}  &\bigm| & \frac{1}{2} \\
    -1 & 2 & -2  &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & -\frac{1}{2}  &\bigm| & -\frac{1}{2} \\
    0 & -\frac{3}{2} & \frac{3}{2}  &\bigm| & \frac{1}{2} \\
    0 & \frac{7}{2} & -\frac{5}{2}  &\bigm| & -\frac{1}{2} \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & \frac{3}{2} & -\frac{1}{2}  &\bigm| & -\frac{1}{2} \\
    0 & -\frac{3}{2} & \frac{3}{2}  &\bigm| & \frac{1}{2} \\
    0 & \frac{7}{2} & -\frac{5}{2}  &\bigm| & -\frac{1}{2} \\
\end{pmatrix}
\xrightarrow{-\frac{2\text{R}_{2}}{3}}
\begin{pmatrix}
    1 & \frac{3}{2} & -\frac{1}{2}  &\bigm| & -\frac{1}{2} \\
    0 & 1 & -1  &\bigm| & -\frac{1}{3} \\
    0 & \frac{7}{2} & -\frac{5}{2}  &\bigm| & -\frac{1}{2} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \frac{3\text{R}_{2}}{2}}
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 1 & -1 &\bigm| & -\frac{1}{3} \\
    0 & \frac{7}{2} & -\frac{5}{2}  &\bigm| & -\frac{1}{2} \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \frac{7\text{R}_{2}}{2}}
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 1 & -1 &\bigm| & -\frac{1}{3} \\
    0 & 0 & 1 &\bigm| & -\frac{2}{3} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & -\frac{2}{3} \\
    0 & 1 & -1 &\bigm| & -\frac{1}{3} \\
    0 & 0 & 1 &\bigm| & -\frac{2}{3} \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & -\frac{2}{3} \\
    0 & 1 & -1 &\bigm| & -\frac{1}{3} \\
    0 & 0 & 1 &\bigm| & -\frac{2}{3} \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & -\frac{2}{3} \\
    0 & 1 & 0 &\bigm| & -\frac{1}{3} \\
    0 & 0 & 1 &\bigm| & -\frac{2}{3} \\
\end{pmatrix}
$
<br>
<br>
\begin{align}
x_1=-\frac{2}{3} \\
x_2=\frac{1}{3} \\
x_3=\frac{2}{3} \\
\end{align}


In [23]:
# 3 c
import numpy as np
A=np.array([[2,3,-1,-1],[1,0,1,0],[-1,2,-2,0]])

A1 = RowScale(A,0,1/2)
print("Eq1:")
print(A1)
A2 = RowAdd(A1,0,1,-1)
print("Eq2:")
print(A2)
A3 = RowAdd(A2,0,2,1)
print("Eq3:")
print(A3)
A4 = RowScale(A3,1,-2/3)
print("Eq4:")
print(A4)
A5 = RowAdd(A4,1,0,-3/2)
print("Eq5:")
print(A5,)
A6 = RowAdd(A5,1,2,-7/2)
print("Eq6:")
print(A6,)
A7 = RowAdd(A6,2,0,-1)
print("Eq7:")
print(A7)
A8 = RowAdd(A7,2,1,1)
print("Eq8:")
print(A8)

print("Solutions x1, x2, x3:")
print(BackwardSubstitution(A8))

Eq1:
[[ 1.   1.5 -0.5 -0.5]
 [ 1.   0.   1.   0. ]
 [-1.   2.  -2.   0. ]]
Eq2:
[[ 1.   1.5 -0.5 -0.5]
 [ 0.  -1.5  1.5  0.5]
 [-1.   2.  -2.   0. ]]
Eq3:
[[ 1.   1.5 -0.5 -0.5]
 [ 0.  -1.5  1.5  0.5]
 [ 0.   3.5 -2.5 -0.5]]
Eq4:
[[ 1.          1.5        -0.5        -0.5       ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          3.5        -2.5        -0.5       ]]
Eq5:
[[ 1.          0.          1.          0.        ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          3.5        -2.5        -0.5       ]]
Eq6:
[[ 1.          0.          1.          0.        ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          0.          1.          0.66666667]]
Eq7:
[[ 1.          0.          0.         -0.66666667]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          0.          1.          0.66666667]]
Eq8:
[[ 1.          0.          0.         -0.66666667]
 [ 0.          1.          0.          0.33333333]
 [ 0.          0.          1.   

4. a. <br>
\begin{pmatrix}
   1 & 0 & 1 \\
   0 & 0 & 3 \\
   0 & 1 & 0 \\
\end{pmatrix}
- is not in row-echelon form because the number 1 in the third row appears to the left of the number 3 in the second row. In row-echelon form, the leading entry in each row should be to the right of the leading entry in the row above it<br><br>
b. <br>
\begin{pmatrix}
   7 & 0 & 1 & 0 \\
   0 & 1 & -1 & 4 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}<br>
-  satisfies the row-echelon form because all rows with nonzero entries are above any rows of all zeros. However, it is not in reduced row-echelon form because the leading entry (the first nonzero entry) in the first row is not 1, which is a requirement for reduced row-echelon form. <br><br>
c. <br>
\begin{pmatrix}
   0 & 1 & 3 & 0 \\
   0 & 0 & 0 & 1 \\
\end{pmatrix}<br>
- is in row-echelon form as it places rows with non-zero entries above rows with all zeros. Moreover, it satisfies the criteria for reduced row-echelon form since all leading entries are 1<br><br>
d. <br>
\begin{pmatrix}
   0 & 0 & 0 \\
   0 & 0 & 0 \\
   0 & 0 & 0 \\
\end{pmatrix}<br>
- is not in row-echelon form as it does not have any rows with non-zero leading entries. It fails to satisfy the basic conditions for row-echelon and reduced row-echelon forms<br><br>
e. <br>
\begin{pmatrix}
   1 & 0 & 3 & -4 & 0 \\
   0 & 0 & 0 & 0 & 0 \\
   0 & 1 & 5 & 0 & 1 \\
\end{pmatrix}<br>
- neither since the row of all 0s are not at the bottom. <bn><br>
f. <br>
\begin{pmatrix}
   0 & 0 & 1 \\
   0 & 1 & 0 \\
   1 & 0 & 0 \\
\end{pmatrix}<br>
- is neither in row-echelon form nor reduced row-echelon form because it violates the condition where rows of all zeros should be at the bottom. <br><br>
g. <br>
\begin{pmatrix}
   1 & 2 & 3 \\
   1 & 0 & 0 \\
   0 & 1 & 1 \\
   0 & 0 & 1 \\
\end{pmatrix}<br>
- is neither in row-echelon form nor reduced row-echelon form because the leading entry in the second row is not to the right of the leading entry in the first row <br><br>
h. <br>
\begin{pmatrix}
   2 & 1 & 3 & 5 \\
   0 & 0 & 1 & -1 \\
   0 & 0 & 0 & 3 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}<br>
- is in row-echelon form, but it is not in reduced row-echelon form because the leading entry of the first row is not 1 <br><br>


5. Solve the following systems of linear equations<br>
a.<br> 
\begin{align}
x_1+2x_2-3x_3=9 \\
2x_1-x_2-x_3=0 \\
4x_1-x_2+x_3=4 \\
\end{align}
<br>
<br>
Solution:
<br>
Reduced row echelon form:
<br>
$
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    2 & -1 & -1  &\bigm| & 0 \\
    4 & -1 & 1  &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & -3  &\bigm| & 9 \\
    0 & -5 & 5  &\bigm| & -18 \\
    4 & -1 & 1  &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 4\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & -3  &\bigm| & 9 \\
    0 & -5 & 5  &\bigm| & -18 \\
    0 & -9 & 13  &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{-\frac{1}{5}\text{R}_{2}}
\begin{pmatrix}
    1 & 2 & -3  &\bigm| & 9 \\
    0 & 1 & -1  &\bigm| & \frac{18}{5} \\
    0 & -9 & 13  &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 2\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & -1  &\bigm| & \frac{9}{5} \\
    0 & 1 & -1  &\bigm| & \frac{18}{5} \\
    0 & -9 & 13  &\bigm| & -32 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & -1  &\bigm| & \frac{9}{5} \\
    0 & 1 & -1  &\bigm| & \frac{18}{5} \\
    0 & -9 & 13  &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + 9\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & -1  &\bigm| & \frac{9}{5} \\
    0 & 1 & -1  &\bigm| & \frac{18}{5} \\
    0 & 0 & 4  &\bigm| & \frac{2}{5} \\
\end{pmatrix}
\xrightarrow{\frac{1}{4}\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & -1  &\bigm| & \frac{9}{5} \\
    0 & 1 & -1  &\bigm| & \frac{18}{5} \\
    0 & 0 & 1  &\bigm| & \frac{1}{10} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0  &\bigm| & \frac{19}{10} \\
    0 & 1 & -1  &\bigm| & \frac{18}{5} \\
    0 & 0 & 1  &\bigm| & \frac{1}{10} \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0  &\bigm| & \frac{19}{10} \\
    0 & 1 & 0  &\bigm| & \frac{37}{10} \\
    0 & 0 & 1  &\bigm| & \frac{1}{10} \\
\end{pmatrix}
$
<br>
<br>
\begin{align}
x_1=-\frac{19}{10} \\
x_2=\frac{37}{10} \\
x_3=\frac{1}{10} \\
\end{align}


In [24]:
# 5
import numpy as np
A=np.array([[1,2,-3,9],[2,-1,-1,0],[4,-1,1,4]])
A1 = RowAdd(A,0,1,-2)
print("Eq1:")
print(A1)
A2 = RowAdd(A1,0,2,-4)
print("Eq2:")
print(A2)
A3 = RowScale(A2,1,-1/5)
print("Eq3")
print(A3)
A4 = RowAdd(A3,1,0,-2)
print("Eq4")
print(A4)
A5 = RowAdd(A4,1,2,9)
print("Eq5")
print(A5)
A6 = RowScale(A5,2,1/4)
print("Eq6")
print(A6)
A7 = RowAdd(A6,2,0,1)
print("Eq7")
print(A7)
A8 = RowAdd(A7,2,1,1)
print("Eq8")
print(A8)

print("Solutions x_1, x_2, x_3:")
print(BackwardSubstitution(A8))

Eq1:
[[  1.   2.  -3.   9.]
 [  0.  -5.   5. -18.]
 [  4.  -1.   1.   4.]]
Eq2:
[[  1.   2.  -3.   9.]
 [  0.  -5.   5. -18.]
 [  0.  -9.  13. -32.]]
Eq3
[[  1.    2.   -3.    9. ]
 [ -0.    1.   -1.    3.6]
 [  0.   -9.   13.  -32. ]]
Eq4
[[  1.    0.   -1.    1.8]
 [ -0.    1.   -1.    3.6]
 [  0.   -9.   13.  -32. ]]
Eq5
[[ 1.   0.  -1.   1.8]
 [-0.   1.  -1.   3.6]
 [ 0.   0.   4.   0.4]]
Eq6
[[ 1.   0.  -1.   1.8]
 [-0.   1.  -1.   3.6]
 [ 0.   0.   1.   0.1]]
Eq7
[[ 1.   0.   0.   1.9]
 [-0.   1.  -1.   3.6]
 [ 0.   0.   1.   0.1]]
Eq8
[[1.  0.  0.  1.9]
 [0.  1.  0.  3.7]
 [0.  0.  1.  0.1]]
Solutions x_1, x_2, x_3:
[1.9 3.7 0.1]


b. <br>
\begin{align}
x+2y= -1 \\
2x+y+z = 1 \\
-x+y-z = -1
\end{align}
<br>
<br>
Solution:
<br>
$
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    2 & 1 & 1  &\bigm| & 1 \\
    -1 & 1 & -1  &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1  &\bigm| & 3 \\
    -1 & 1 & -1  &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{1}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1  &\bigm| & 3 \\
    0 & 3 & -1  &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{-\frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & 1 & -\frac{1}{3}  &\bigm| & -1 \\
    0 & 3 & -1  &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 2\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & \frac{2}{3} &\bigm| & 1 \\
    0 & 1 & -\frac{1}{3}  &\bigm| & -1 \\
    0 & 3 & -1  &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 3\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & \frac{2}{3} &\bigm| & 1 \\
    0 & 1 & -\frac{1}{3}  &\bigm| & -1 \\
    0 & 0 & 0  &\bigm| & 1 \\
\end{pmatrix}
$
<br>
<br>
$\therefore$ no solutions

In [27]:
# 5
import numpy as np

A=np.array([[1,2,0,-1],[2,1,1,1],[-1,1,-1,-1]])

A1 = RowAdd(A,0,1,-2)
print("A1")
print(A1)
A2 = RowAdd(A1,0,2,1)
print("A2")
print(A2)
A3 = RowScale(A2,1,-1/3)
print("A3")
print(A3)
A4 = RowAdd(A3,1,0,-2)
print("A4")
print(A4)
A5 = RowAdd(A4,1,2,-3)
print("A5")
print(A5)


print("Solutions x y z:")
print(BackwardSubstitution(A5))

A1
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [-1.  1. -1. -1.]]
A2
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [ 0.  3. -1. -2.]]
A3
[[ 1.          2.          0.         -1.        ]
 [-0.          1.         -0.33333333 -1.        ]
 [ 0.          3.         -1.         -2.        ]]
A4
[[ 1.          0.          0.66666667  1.        ]
 [-0.          1.         -0.33333333 -1.        ]
 [ 0.          3.         -1.         -2.        ]]
A5
[[ 1.          0.          0.66666667  1.        ]
 [-0.          1.         -0.33333333 -1.        ]
 [ 0.          0.          0.          1.        ]]
Solutions x y z:
[nan inf inf]


C:\Users\queen\AppData\Local\Temp\ipykernel_3816\121720578.py:8: RuntimeWarning: divide by zero encountered in scalar divide
  x[i] = Ab[i, n - 1] / Ab[i, i]
C:\Users\queen\AppData\Local\Temp\ipykernel_3816\121720578.py:10: RuntimeWarning: invalid value encountered in scalar multiply
  Ab[k, n - 1] -= Ab[k, i] * x[i]


c. <br>
\begin{align}
x_1-3x_2-2x_3=0 \\
-x_1+2x_2+x_3=0 \\
2x_1+4x_2+6x_3=0 \\
\end{align}
<br>
<br>
Solution:
<br>
Reduced row echelon form:
<br>
$
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    -1 & 2 & 1  &\bigm| & 0 \\
    2 & 4 & 6  &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1  &\bigm| & 0 \\
    2 & 4 & 6  &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1  &\bigm| & 0 \\
    0 & 10 & 10  &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{-\text{R}_{2}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & 1 & 1  &\bigm| & 0 \\
    0 & 10 & 10  &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + 3\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 1 & 1  &\bigm| & 0 \\
    0 & 10 & 10  &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 10\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 1 & 1  &\bigm| & 0 \\
    0 & 0 & 0  &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$\therefore$ infinite solutions


In [32]:
# c
import numpy as np
A=np.array([[1,-3,-2,0],[-1,2,1,0],[2,4,6,0]])

A1 = RowAdd(A,0,1,1)
print("Eq1")
print(A1)
A2 = RowAdd(A1,0,2,-2)
print("Eq2")
print(A2)
A3 = RowScale(A2,1,-1)
print("Eq3")
print(A3)
A4 = RowAdd(A3,1,0,3)
print("Eq4")
print(A4,)
A5 = RowAdd(A4,1,2,-10)
print("Eq5")
print(A5)

print("Solutions x_1, x_2, x_3:")
print(BackwardSubstitution(A5))

Eq1
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 2.  4.  6.  0.]]
Eq2
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 0. 10. 10.  0.]]
Eq3
[[ 1. -3. -2.  0.]
 [-0.  1.  1. -0.]
 [ 0. 10. 10.  0.]]
Eq4
[[ 1.  0.  1.  0.]
 [-0.  1.  1. -0.]
 [ 0. 10. 10.  0.]]
Eq5
[[ 1.  0.  1.  0.]
 [-0.  1.  1. -0.]
 [ 0.  0.  0.  0.]]
Solutions x_1, x_2, x_3:
[nan nan nan]


C:\Users\queen\AppData\Local\Temp\ipykernel_3816\121720578.py:8: RuntimeWarning: invalid value encountered in scalar divide
  x[i] = Ab[i, n - 1] / Ab[i, i]
